# FAISS (Facebook AI Similarity Search)

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import torch
from plantclef.config import get_device

print(f"PyTorch Version: {torch.__version__}")
device = get_device()
print(f"Using device: {device}")

PyTorch Version: 2.6.0+cu124
Using device: cuda

In [3]:
import pandas as pd
from pathlib import Path

# Get list of stored filed in cloud bucket
root = Path().resolve().parents[0]
print(root)
! date

/storage/home/hcoda1/9/mgustineli3/clef/pytorch-plantclef
Mon Mar 24 10:10:13 AM EDT 2025

In [5]:
# path to data
data_path = f"{root}/data/embeddings"
train_path = f"{data_path}/train_embeddings"
test_path = f"{data_path}/test_grid_3x3_embeddings"

# read train/test data
train_df = pd.read_parquet(train_path)
test_df = pd.read_parquet(test_path)

# display data
print(f"Train DF shape: {train_df.shape}")
print(f"Test DF shape: {test_df.shape}")
display(train_df.head(3))
display(test_df.head(3))

Train DF shape: (2020, 6)
Test DF shape: (1800, 6)

,image_name,data,embeddings,logits,tile,partition
0,28e2fbd0cc93d82d7de3ed5783c64816074955e0.jpg,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00...,"[0.22075553238391876, -0.5152621269226074, 0.7...","{""1389294"": 0.4966914653778076, ""1356390"": 0.0...",0,0
1,47b5db375e741fdc09b5e133d5bfef0285aa695c.jpg,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00...,"[0.55893474817276, 0.19274836778640747, 0.8937...","{""1418612"": 0.7230438590049744, ""1390910"": 0.0...",0,0
2,c6a6b172ab03374ad1bb713b7e7b37dd84f094a1.jpg,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00...,"[-0.15363329648971558, 0.35160958766937256, 0....","{""1722578"": 0.8078303337097168, ""1411700"": 0.0...",0,0

,image_name,data,embeddings,logits,tile,partition
0,CBN-PdlC-C4-20180723.jpg,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,"[-1.3391107320785522, 1.6340396404266357, -2.2...","""{\""1741880\"": 0.1965922713279724, \""1729043\""...",0,0
1,CBN-PdlC-C4-20180723.jpg,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,"[-0.11381672322750092, 1.790043830871582, -0.5...","""{\""1395807\"": 0.19840383529663086, \""1741880\...",1,0
2,CBN-PdlC-C4-20180723.jpg,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,"[-0.40855133533477783, 1.9910684823989868, -0....","""{\""1395807\"": 0.4447108805179596, \""1397468\""...",2,0

In [ ]:
import torch
from plantclef.config import get_device


class FaissClassifier:
    def __init__(self, train_embeddings):
        self.train_embeddings = train_embeddings
        self.device = get_device()

    def build_index(self, train_embeddings):
        pass

    def make_predictions(self, embeddings):
        pass